
        <div class="inner-elecuid-page">
			<div class="inner-page-title"><h1>E-LIQUID</h1></div>
			<section class="top-3col-sec">
				<div class="row">
					<div class="col-lg-3">
					 <p>
This is where the magic happens. Having the correct equipment is important, having a go-to list of favorite e-liquid flavors 
is essential. Cloudscape Vape is your home for the tastiest e-liquid flavors from the best brands for quality and value. We 
have smooth all-day vapes for those never-ending sessions, and rare treats with more intense flavors you'll want to savor. Be 
a part of our community: read our e-liquid reviews and contribute your own. Cloudscape Vape is where good vaping happens!
</p></div>
					<div class="col-lg-6 featurebnner">
					  <img src="<?php echo $block->getViewFileUrl('images/eliquid-featurebanner.jpg'); ?>" alt="">
					  <a href="#">Learn more</a>
					</div>
					<div class="col-lg-3 elq-secondarybanner"><img src="<?php echo $block->getViewFileUrl('images/secondary-product.jpg'); ?>" alt=""></div>
				</div>
			</section>
	<section class="top10eliquid">
      <div class="row">
        <div class="large-12 columns">
		<h2>TOP 10 E-LIQUID</h2>
          <div class="owl-carousel owl-theme">
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
             <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
             <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>
            <div class="item">
              <div class="top10pro-img">
				<a href="#"><img src="<?php echo $block->getViewFileUrl('images/popular-cat-eliquid.jpg'); ?>" alt=""></a>				
			  </div>
			  <div class="pro-sl-option">
				<h5>Product Name</h5>
				<div class="price-n-star">
				  <div class="dprice">
				     <span>$00.00</span>
				  </div>
					<div class="product-reviews-summary short">
							<div class="rating-summary">
							<span class="label"><span>Rating:</span></span>
							<div title="100%" class="rating-result">
								<span style="width:100%"><span>100%</span></span>
							</div>
						    </div>
							<div class="reviews-actions">
							<a href="#" class="action view">(2)</span></a>
						</div>
					</div>
				</div>
				<div class="selNcart"><a class="selNcart-btn" href="#">Select Options</a></div>
			  </div>
            </div>            
          </div>
     </div>
    </div>
</section>

<section class="flavors-cat">
	<div class="row">
		<h2>SHOP OUR E-LIQUID FLAVOR CATEGORIES</h2>
		<ul class="fl-category-list">
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/cafe-flavors.png'); ?>" alt="">
					<span>CAFE FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/candy-flavors.png'); ?>" alt="">
					<span>CANDY FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/cream-flavors.png'); ?>" alt="">
					<span>CREAM FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/dessert-flavor.png'); ?>" alt="">
					<span>DESSERT FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/drink-flavors.png'); ?>" alt="">
					<span>DRINK FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/fruit-flavors.png'); ?>" alt="">
					<span>FRUIT FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/menthol-flavors.png'); ?>" alt="">
					<span>MENTHOL FLAVORS</span>
				</a>
			</li>
			<li>
				<a href="#">
					<img src="<?php echo $block->getViewFileUrl('images/tobacco-flavors.png'); ?>" alt="">
					<span>TOBACCO FLAVORS</span>
				</a>
			</li>
		</ul>
	</div>
</section>	

<section class="our-prem-brands">
<div class="row">
<h2>SHOP OUR E-LIQUID PREMIUM BRANDS (279)</h2>
<div class="brands-nm">
<h5>Filter Brands:</h5>
<ul class="sl-brandname">
	<li><span>All Brands<span></li>
	<li><span>A</span></li>
	<li><span>B</span></li>
	<li><span>C</span></li>
	<li><span>D</span></li>
	<li><span>E</span></li>
	<li><span>F</span></li>
	<li><span>G</span></li>
	<li><span>H</span></li>
	<li><span>I</span></li>
	<li><span>J</span></li>
	<li><span>K</span></li>
	<li><span>L</span></li>
	<li><span>M</span></li>
	<li><span>N</span></li>
	<li><span>O</span></li>
	<li><span>P</span></li>
	<li><span>Q</span></li>
	<li><span>R</span></li>
	<li><span>S</span></li>
	<li><span>T</span></li>
	<li><span>U</span></li>
	<li><span>V</span></li>
	<li><span>W</span></li>
	<li><span>X</span></li>
	<li><span>Y</span></li>
	<li><span>Z</span></li>
</ul>

</div>
<div class="brnds-logoImg">
<ul class="">
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></a></li>
	<li><a href="#"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></a></li>
</ul>
</div>

</div>
</section>

			
</div>
		
		<script type="text/javascript">		
		
			require([
				"jquery",
				"owlcarousel"
			], function($){
			//<![CDATA[
			
				var owl = $('.owl-carousel');
				owl.owlCarousel({
					loop: true,
					margin: 10,
					dots: false,
					responsiveClass: true,
					responsive: {
						0: {
							items: 1,
							nav: true
						},
						600: {
							items: 3,
							nav: true
						},
						1000: {
							items: 5,
							nav: true,
							loop: false,
							margin: 20
						}
					}
				});
			 //]]>
		});
		</script>
		
