<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php $_postCollection = $block->getPostCollection(); ?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-recent-posts cls-posts" data-bind="scope: 'recemt-posts'">
    <div class="block-title">
        <h4><?php echo __('News Update') ?></h4>
    </div>
    <div class="block-content">
        <?php foreach ($_postCollection as $_post) { ?>
            <div class="item">                
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                <div class="post-ftimg-hld">
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <img src="<?php echo $featuredImage ?>" alt="<?php echo $block->escapeHtml($_post->getTitle()) ?>" style="width: 125px;" />
                    </a>
                </div>
                <?php } ?>
                
                <h5>
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()) ?>
                    </a>
                </h5>
                
                <div class="cls-short-desc">
                    <p><?php echo substr(strip_tags($_post->getContent()),0,175).'...'; ?><br/><a href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read full') ?></a></p>
                </div>
                
            </div>
        <?php } ?>
    </div>
</div>
<?php } ?>