<section class="home-quickaccess">
	<h1 class="section-title"><span>Quick</span> Access</h1>
		<div class="col-lg-6 col-sm-6">
			<div class="row">
			 <div class="col-lg-6 col-sm-6 col-xs-6 col-xss-12">
				 <div class="vapekitbuilder">
				<img src="<?php echo $block->getViewFileUrl('images/vapekit-builder.jpg'); ?>" alt="">
				<a class="vapekitbuilder-link" href="javascript:void(0)">Vape Kit Builder <i class="fa fa-angle-double-right" aria-hidden="true"></i>
</a>
					<p>Learn how to build your own coils with your built kit! Understand how each tool works with ease.</p>
					</div>
				</div>
				<div class="col-lg-6 col-sm-6 col-xs-6 col-xss-12">
					<div class="newvaping">
					<img src="<?php echo $block->getViewFileUrl('images/new2vaping.jpg'); ?>" alt="">
					<a class="newvaping-link" href="javascript:void(0)">Vape Kit Builder <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
					<p>If you’re new to vaping, let’s get you started on switching the habit! Check out our beginner devices!</p>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6 col-sm-6">	
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('quick_access')->toHtml();?>
		</div>
</section>
    
	<?php echo $this->getLayout()->createBlock("Techievolve\PopularCategory\Block\Category")->setTemplate("Techievolve_PopularCategory::category.phtml")->toHtml(); ?>

	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop_the_csvape_lyfestyle')->toHtml();?>


	<div class="dottedbg-divider">&nbsp;</div>       
	
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('join-our-programs-to-receive')->toHtml();?>

	<div class="dottedbg-divider">&nbsp;</div>

	<section class="thnks-partner">
		 <h2 class="center-title">Special Thanks<br> <span>To Our Partners</span></h2>
		 <div class="thnks-partner-blue">
		 <div class="row">
			<div class="col-lg-6 col-md-6 col-sm-6">
				<h3>E-Liquid Brands</h3>
				<div class="proBrands">
					<div class="owl-carousel owl-theme brandslider">
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/brand4.png'); ?>" alt=""></div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6">
				<h3>Product Brands</h3>
				<div class="proBrands">
					<div class="owl-carousel owl-theme brandslider">
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand1.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand2.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand3.png'); ?>" alt=""></div>
						<div class="item"><img src="<?php echo $block->getViewFileUrl('images/pro-brand4.png'); ?>" alt=""></div>
					</div>
				</div>
			</div>
		 </div>
	   </div>
	</section> 

	<section class="bottom-section">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-3">
				<div class="csvape-comunity">
					<h3><span>CSVAPE</span> Community</h3>
					<div class="news-updte">
						<h4>News Update</h4>
						<img src="<?php echo $block->getViewFileUrl('images/newsimg.jpg'); ?>" alt="">
						<h5>VGOD Product</h5>
						<p>Check out VGOD’s new product on the market ready for enjoyment! The new product has been created to amaze all, and satisfy your taste bud cravings! Click for more information and learn what’s new from VGOD. <a href="javascript:void(0)">Read full</a></p>
						<a class="mornews" href="#">More News</a>
					</div>
					 <div class="news-updte cspoll">
						<h4>CSVAPE Poll</h4>                    
						<p>How many cigarettes a day did you smoke before vaping?</p>
						<form class="smkoking-poll">
							 <div class="form-group"><input type="radio"> <label>1-10 a day</label></div>
							  <div class="form-group"><input type="radio"> <label>11-20 a day</label></div>
							  <div class="form-group"><input type="radio"> <label>21+  a day</label></div>  
							</form> 
						<a class="mornews" href="#">More News</a>
					</div>
				</div>
			</div>
			<div class="col-lg-9 col-md-9 col-sm-9">				
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('best_kept_secrets')->toHtml();?>
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('superior_service')->toHtml();?>
			</div>
		</div>
	</section>      
        
</div>   
