<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();
$brands     = $block->getBrands();
?>


<ul class="cd-dropdown-content cls-first-level">
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('csvape_before_menu')->toHtml();?>	
    <?php
    // Loop through categories
    foreach ( $categories as $category ) :
        ?>
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?> <?php echo $category->hasChildren()?'has-children':''; ?>">
            <a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="nav_<?php echo $category->getUrlKey(); ?><?php echo($block->isActive($category) ? ' active' : ''); ?>">
                <?php echo $category->getName(); ?>
            </a>
            <?php if ( $category->hasChildren() ) : ?>
                <?php /* <span class="expand"><?php echo $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span> */ ?>
				<?php echo $block->getChildCategoryView($category); ?>
            <?php endif; ?>

            
        </li>
    <?php endforeach; ?>
	<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('csvape_after_menu')->toHtml();?>
</ul>
<script type="text/javascript">
	/* Simply invoke iffe of sidebarmodule */
	require(['jquery','sidebarmodule'], function ($) {});
</script>