	<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
	
	<div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px; height: 430px; background: #fff; overflow: hidden; ">       
	<!-- Slides Container -->
	<div u="slides" style="cursor: move; position: absolute; left:0px; top: 0px; width: 600px; height: 300px; overflow: hidden;">
		<div>
			<a class="sl-item" href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-big.jpg'); ?>" alt="">
			 <div class="sl-caplink"><h3>Today's Deals</h3><span>Deal Now <i class="fa fa-play" aria-hidden="true"></i></span></div>
			</a>
			<div u="thumb"><img src="<?php echo $block->getViewFileUrl('images/todays-deal-sm.jpg'); ?>" alt=""><h5>Today's Deals</h5></div>
		</div>
		
		<!--Top E-liquid Products-->
		
		<?php $topEliquid = $this->getTopEliquidProduct(); ?>
		<?php if($topEliquid): ?>
			<div id="product-<?php echo $topEliquid->getId() ?>">
				<a class="sl-item" href="<?php echo $topEliquid->getProductUrl() ?>">
					<img src="<?php echo $_imagehelper->init($topEliquid, 'home_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(565, 283)->getUrl(); ?>" alt="">
					<div class="sl-caplink">
						<h3><?php echo __('Top E-liquid') ?></h3>
						<span><?php echo __('Explore Now') ?><i class="fa fa-play" aria-hidden="true"></i></span>
					</div>
				</a>
				<div u="thumb">
					<img src="<?php echo $_imagehelper->init($topEliquid, 'home_thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(106, 90)->getUrl(); ?>" alt="">
					<h5><?php echo __('Top E-liquid') ?></h5>
				</div>
			</div>
		<?php endif; ?>
		
		<!--Top Devices Products-->
		
		<?php $topDevices = $this->getTopDevicesProduct(); ?>
		<?php if($topDevices): ?>
			<div id="product-<?php echo $topDevices->getId() ?>">
				<a class="sl-item" href="<?php echo $topDevices->getProductUrl() ?>">
					<img src="<?php echo $_imagehelper->init($topDevices, 'home_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(565, 283)->getUrl(); ?>" alt="">
					<div class="sl-caplink">
						<h3><?php echo __('Top Devices') ?></h3>
						<span><?php echo __('Explore Now') ?><i class="fa fa-play" aria-hidden="true"></i></span>
					</div>
				</a>
				<div u="thumb">
					<img src="<?php echo $_imagehelper->init($topDevices, 'home_thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(106, 90)->getUrl(); ?>" alt="">
					<h5><?php echo __('Top Devices') ?></h5>
				</div>
			</div>
		<?php endif; ?>
		
		<!--Featured Products-->
		
		<?php $featuredProduct = $this->getFeaturedProduct(); ?>
		<?php if($featuredProduct): ?>
			<div id="product-<?php echo $featuredProduct->getId() ?>">
				<a class="sl-item" href="<?php echo $featuredProduct->getProductUrl() ?>">
					<img src="<?php echo $_imagehelper->init($featuredProduct, 'home_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(565, 283)->getUrl(); ?>" alt="">
					<div class="sl-caplink">
						<h3><?php echo __('Featured Products') ?></h3>
						<span><?php echo __('Explore Now') ?><i class="fa fa-play" aria-hidden="true"></i></span>
					</div>
				</a>
				<div u="thumb">
					<img src="<?php echo $_imagehelper->init($featuredProduct, 'home_thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(106, 90)->getUrl(); ?>" alt="">
					<h5><?php echo __('Featured Products') ?></h5>
				</div>
			</div>
		<?php endif; ?>
		
		<!--New Arrivals-->
		
		<?php  $newProduct = $this->getNewArrivals(); ?> 
		<?php if($newProduct): ?>
			<div id="product-<?php echo $newProduct->getId() ?>">
				<a class="sl-item" href="<?php echo $newProduct->getProductUrl() ?>">
					<img src="<?php echo $_imagehelper->init($newProduct, 'home_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(565, 283)->getUrl(); ?>" alt="">
					<div class="sl-caplink">
						<h3><?php echo __('New Arrivals') ?></h3>
						<span><?php echo __('Explore Now') ?><i class="fa fa-play" aria-hidden="true"></i></span>
					</div>
				</a>
				<div u="thumb">
					<img src="<?php echo $_imagehelper->init($newProduct, 'home_thumbnail')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(106, 90)->getUrl(); ?>" alt="">
					<h5><?php echo __('New Arrivals') ?></h5>
				</div>
			</div>
		<?php endif; ?>
		
		 
	</div>
	
	<!-- ThumbnailNavigator Skin Begin -->
	<div u="thumbnavigator" class="jssort14" style="position: absolute; width: 600px; height: 120px; left:0px; bottom: 0px;background:#fff;">
		<!-- Thumbnail Item Skin Begin -->
		<style>
			/* jssor slider thumbnail navigator skin 14 css */
			/*
			.jssort14 .p            (normal)
			.jssort14 .p:hover      (normal mouseover)
			.jssort14 .pav          (active)
			.jssort14 .pav:hover    (active mouseover)
			.jssort14 .pdn          (mousedown)
			*/
			.jssort14 .w, .jssort14 .phv .w
			{
				cursor: pointer;
				position: absolute;
				WIDTH: 100%;
				HEIGHT: 100%;
				background-color: transparent;
			}
			.jssort14 .pdn .w, .jssort14 .pav .w, .jssort14 .p:hover .w
			{
				background-color: transparent;
			}
			.jssort14 .c
			{
				color: #000;
				font-size:13px;
				background-color: transparent;               	
				
			}
			.jssort14 .p:hover .c, .jssort14 .phv .c, .jssort14 .pav:hover .c, .jssort14 .pav .c
			{
				transition: none;
				-moz-transition: none;
				-webkit-transition: none;
				-o-transition: none;
			}
			.jssort14 .pav .c
			{
				
			}
			.jssort14 .p:hover .c, .jssort14 .phv .c, .jssort14 .pav:hover .c
			{
				
			}
		</style>
  <div u="slides" style="cursor: move; width:600px; top:0px; left:0px;">
	<div u="prototype" class="p" style="POSITION: absolute; WIDTH: 120px; HEIGHT: 120px; TOP: 0; LEFT: 0; padding:0px; background:#fff;">
	  <div class=w>
	   <div u="thumbnailtemplate" class="c" style=" WIDTH: 100%; HEIGHT: 120px; position:absolute; TOP: 0; LEFT: 0; line-height:23px; text-align:center;">
				</div>
				</div>
			  </div>
			</div>
		</div>
		
	   
	</div>
