<div class="row superior-service">
    <h4>SUPERIOR SERVICE &amp; PREMIUM QUALITY PRODUCTS</h4>
    <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
     <div class="sp-block">
         <div class="icoBlock">
             <i class="fa fa-globe" aria-hidden="true"></i>
            </div>
            <div class="descBlock">
                <h1><?php echo $this->getCustomerCount(); ?></h1>
                <p>WorldWide Customers</p>
            </div>
        </div>                    
    </div>
     <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
     <div class="sp-block">
         <div class="icoBlock">
             <i class="fa fa-star" aria-hidden="true"></i>
            </div>
            <div class="descBlock">
             <h1><?php echo $this->getReviewsCount(); ?></h1>
                <p>Product Reviews</p>
            </div>
        </div>                    
    </div>
     <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
     <div class="sp-block">
         <div class="icoBlock">
             <i class="fa fa-eyedropper" aria-hidden="true"></i>
            </div>
            <div class="descBlock">
             <h1><?php echo $this->getEliquidFlavorsCount(); ?></h1>
                <p>E-Liquid Flavors</p>
            </div>
        </div>                    
    </div>
     <div class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col-xss-12">
     <div class="sp-block">
         <div class="icoBlock">
             <img src="http://192.168.0.127/csvape/pub/static/frontend/Techievolve/csvape/en_US/images/vape-ico.png" alt="">
            </div>
            <div class="descBlock">
             <h1><?php echo $this->getVapeProductsCount(); ?></h1>
                <p>Vape Products</p>
            </div>
        </div>                    
    </div>                
</div>
